./policy --inference Gibbs --blockpolicy  --name test/ocr/f4/blockpolicy/cond/0/tcall --K 1 --numThreads 10 --model model/ocr_f4.model --unigram_model model/ocr_f1.model --scoring Acc --windowL 0 --trainCount 99999 --testCount 99999 --depthL 0 --factorL 4 --verbose false --train data/ocr/train0 --test data/ocr/test0 --eta 1 --T 8 --c 0 --dataset ocr --feat "cond-ent bias log-#sp #sp"
./policy --inference Gibbs --blockpolicy  --name test/ocr/f4/blockpolicy/unigram/0/tcall --K 1 --numThreads 10 --model model/ocr_f4.model --unigram_model model/ocr_f1.model --scoring Acc --windowL 0 --trainCount 99999 --testCount 99999 --depthL 0 --factorL 4 --verbose false --train data/ocr/train0 --test data/ocr/test0 --eta 1 --T 8 --c 0 --dataset ocr --feat "unigram-ent bias log-#sp #sp"
./policy --inference Gibbs --blockpolicy  --name test/ocr/f4/blockpolicy/01-unigram/0/tcall --K 1 --numThreads 10 --model model/ocr_f4.model --unigram_model model/ocr_f1.model --scoring Acc --windowL 0 --trainCount 99999 --testCount 99999 --depthL 0 --factorL 4 --verbose false --train data/ocr/train0 --test data/ocr/test0 --eta 1 --T 8 --c 0 --dataset ocr --feat "01-unigram-ent bias log-#sp #sp"
./policy --inference Gibbs --blockpolicy  --name test/ocr/f4/blockpolicy/inv-unigram/0/tcall --K 1 --numThreads 10 --model model/ocr_f4.model --unigram_model model/ocr_f1.model --scoring Acc --windowL 0 --trainCount 99999 --testCount 99999 --depthL 0 --factorL 4 --verbose false --train data/ocr/train0 --test data/ocr/test0 --eta 1 --T 8 --c 0 --dataset ocr --feat "inv-unigram-ent bias log-#sp #sp"
./policy --inference Gibbs --blockpolicy  --name test/ocr/f4/blockpolicy/logistic-unigram/0/tcall --K 1 --numThreads 10 --model model/ocr_f4.model --unigram_model model/ocr_f1.model --scoring Acc --windowL 0 --trainCount 99999 --testCount 99999 --depthL 0 --factorL 4 --verbose false --train data/ocr/train0 --test data/ocr/test0 --eta 1 --T 8 --c 0 --dataset ocr --feat "logistic-unigram-ent bias log-#sp #sp"
./policy --inference Gibbs --blockpolicy  --name test/ocr/f4/blockpolicy/nb-#vary/0/tcall --K 1 --numThreads 10 --model model/ocr_f4.model --unigram_model model/ocr_f1.model --scoring Acc --windowL 0 --trainCount 99999 --testCount 99999 --depthL 0 --factorL 4 --verbose false --train data/ocr/train0 --test data/ocr/test0 --eta 1 --T 8 --c 0 --dataset ocr --feat "nb-#vary bias log-#sp #sp"
./policy --inference Gibbs --blockpolicy  --name test/ocr/f4/blockpolicy/all/0/tcall --K 1 --numThreads 10 --model model/ocr_f4.model --unigram_model model/ocr_f1.model --scoring Acc --windowL 0 --trainCount 99999 --testCount 99999 --depthL 0 --factorL 4 --verbose false --train data/ocr/train0 --test data/ocr/test0 --eta 1 --T 8 --c 0 --dataset ocr --feat "nb-#vary 01-unigram-ent cond-ent bias log-#sp #sp"



